export const SET_IMAGE_START = "SET_IMAGE_START";
export const SET_IMAGE_PENDING = "SET_IMAGE_PENDING";
export const SET_IMAGE_SUCCESS = "SET_IMAGE_SUCCESS";
export const SET_IMAGE_FAILURE = "SET_IMAGE_FAILURE";

export const GET_IMAGES_START = "GET_IMAGES_START";
export const GET_IMAGES_PENDING = "GET_IMAGES_PENDING";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_IMAGES_FAILURE = "GET_IMAGES_FAILURE";

export const REMOVE_IMAGE_START = "REMOVE_IMAGE_START";
export const REMOVE_IMAGE_PENDING = "REMOVE_IMAGE_PENDING";
export const REMOVE_IMAGE_SUCCESS = "REMOVE_IMAGE_SUCCESS";
export const REMOVE_IMAGE_FAILURE = "REMOVE_IMAGE_FAILURE";
